host: localost:8088
info:
  contact:
    email: 541304803@qq.com
    name: Blog Api
    url: https://github.com/yin5th
  description: 博客简单的api.
  license: {}
  termsOfService: https://github.com/yin5th/gin_blog
  title: 博客API
  version: v1
paths:
  /api/v1/articles:
    get:
      parameters:
      - description: TagID
        in: query
        name: tag_id
        type: integer
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":[{"id":3,"created_at":1516937037,"modified_at":0,"tag_id":11,"tag":{"id":11,"created_on":1516851591,"modified_on":0,"name":"312321","created_by":"4555","modified_by":"","state":1},"content":"5555","created_by":"2412","modified_by":"","state":1}],"msg":"ok"}'
          schema:
            type: string
      summary: 获取多个文章
      tags:
      - article
    post:
      parameters:
      - description: TagID
        in: formData
        name: tag_id
        required: true
        type: integer
      - description: Title
        in: formData
        name: title
        required: true
        type: string
      - description: Desc
        in: formData
        name: desc
        required: true
        type: string
      - description: Content
        in: formData
        name: content
        required: true
        type: string
      - description: CreatedBy
        in: formData
        name: created_by
        required: true
        type: string
      - description: State
        in: formData
        name: state
        required: true
        type: integer
      - description: CoverImageUrl
        in: formData
        name: cover_image_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"message":"ok"}'
          schema:
            type: string
      summary: 新增文章
      tags:
      - article
  /api/v1/articles/{id}:
    delete:
      parameters:
      - {}
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":400,"data":{},"message":"请求参数错误"}'
          schema:
            type: string
      summary: 删除文章
      tags:
      - article
    get:
      parameters:
      - {}
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":3,"created_on":1516937037,"modified_on":0,"tag_id":11,"tag":{"id":11,"created_on":1516851591,"modified_on":0,"name":"312321","created_by":"4555","modified_by":"","state":1},"content":"5555","created_by":"2412","modified_by":"","state":1},"message":"ok"}'
          schema:
            type: string
      summary: 获取单个文章
      tags:
      - article
    put:
      parameters:
      - {}
      - description: TagID
        in: formData
        name: tag_id
        type: string
      - description: Title
        in: formData
        name: title
        type: string
      - description: Desc
        in: formData
        name: desc
        type: string
      - description: Content
        in: formData
        name: content
        type: string
      - description: ModifiedBy
        in: formData
        name: modified_by
        required: true
        type: string
      - description: State
        in: formData
        name: state
        type: integer
      - description: CoverImageUrl
        in: formData
        name: cover_image_url
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":400,"data":{},"msg":"请求参数错误"}'
          schema:
            type: string
      summary: 修改文章
      tags:
      - article
  /api/v1/tags:
    get:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: State
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"lists":[{"id":3,"created_at":1516849721,"modified_at":0,"name":"3333","created_by":"4555","modified_by":"","state":0}],"total":29},"message":"ok"}'
          schema:
            type: string
      summary: 获取符合条件的标签列表
      tags:
      - tag
    post:
      parameters:
      - {}
      - {}
      - {}
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200, "data":{}, "message":"ok'
          schema:
            type: string
      summary: 新增文章标签
      tags:
      - tag
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"message":"ok"}'
          schema:
            type: string
      summary: 删除文章标签
      tags:
      - tag
    put:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: modified_by
        in: formData
        name: modified_by
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"message":"ok"}'
          schema:
            type: string
      summary: 修改文章标签
      tags:
      - tag
securityDefinitions:
  OAuth2Password:
    flow: password
    tokenUrl: /auth
    type: oauth2
swagger: "2.0"
